server:
    port: 9129
spring:
    application:
        name: yejjconfig-server
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://119.3.171.141:3316/yejjconfig?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456a!
#    sql:
#        #每次启动时，自动创建表并重新插入数据
#        init:
#            schema-locations: classpath:db.sql
#            mode: always
#    h2:
#      console:
#          enabled: true
#          path: /h2
#          settings:
#              web-allow-others: true
mybatis:
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl